import React from 'react'

import { Header, Container } from '@/shared/components/shared'

export const metadata = {
    title: 'Next Pizza | Корзина',
    description: 'Generated by Next.js',
}

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
    return (
        <main className="min-h-screen bg-[#F4F1EE]">
            <Container>
                <Header className="border-b-gray-200" hasSearch={false} hasCart={false} />
                {children}
            </Container>
        </main>
    )
}
